[package]
name = "magic_square_of_squares"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
once_cell = "1.20.2"
rayon = "1.10.0"
rusqlite = "0.32.1"
